#tools.py
from config import *
from utils import *
import os
import re

def read_wiki_page(file_name: str) -> str:
    """
    Safely opens and reads a file from the local Wiki directory.
    Returns the file content, or a descriptive message for the LLM if the file doesn't exist.
    """
    # Clean up any potential rogue spaces or markdown quotes generated by the LLM
    file_name = file_name.strip(" '\"`‌")
    
    # Ensure the file has the correct extension
    if not file_name.endswith('.md'):
        file_name += '.md'
        
    file_path = os.path.join(WIKI_DIR, file_name)
    
    if os.path.exists(file_path):
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                return f.read()
        except Exception as e:
            return f"❌ Error reading file '{file_name}': {str(e)}"
    else:
        # We return a constructive prompt instead of throwing a hard error.
        # This tells the LLM that it's allowed to create this file from scratch.
        return f"⚠️ Fișierul '{file_name}' nu există încă în Wiki. Îl poți crea acum folosind acțiunea CREATE_PAGE."
 


def patch_index(section_target: str, new_line_text: str) -> str:
    """
    Inserts a new markdown link line under a specific pre-existing section in index.md.
    Does NOT create a new section if it is missing. Prevents duplicate link placement.
    """
    index_path = os.path.join(WIKI_DIR, "index.md")
    
    # Return an error immediately if the base index file is missing
    if not os.path.exists(index_path):
        return "❌ Eroare critică: Fișierul 'index.md' nu există pe disc."

    with open(index_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    # Create the normalized key for matching
    target_clean = clean_header_title(section_target)
    
    # Extract the requested wiki-link inside [[...]] to check for duplicates
    link_match = re.search(r'\[\[(.*?)\]\]', new_line_text)
    extracted_link = link_match.group(1).strip() if link_match else None

    section_found = False
    target_index = -1

    # Step 1: Look for the target section header line
    for idx, line in enumerate(lines):
        if line.strip().startswith('#'):
            if clean_header_title(line) == target_clean:
                section_found = True
                target_index = idx
                break

    # Step 2: Handle insertion if the section exists
    if section_found:
        # Check if this exact wiki link already exists under this specific section
        for i in range(target_index + 1, len(lines)):
            if lines[i].strip().startswith('#'):
                break  # Stopped because we reached a new section header
            if extracted_link and f"[[{extracted_link}]]" in lines[i]:
                return f"ℹ️ Link-ul [[{extracted_link}]] există deja în secțiunea '{section_target}', nu a fost duplicat."
        
        # Insert right below the section header line
        lines.insert(target_index + 1, f"{new_line_text.strip()}\n")
        
        with open(index_path, 'w', encoding='utf-8') as f:
            f.writelines(lines)
        return f"✅ Succes: Am adăugat linia în index.md sub secțiunea existentă '{section_target}'."

    # Step 3: If the section doesn't match anything, reject the edit
    else:
        return f"❌ Eroare: Secțiunea '{section_target}' nu a fost găsită în index.md. AI-ul NU are voie să creeze secțiuni noi în index. Te rog folosește una dintre secțiunile sau facultățile oficiale existente."



def patch_wiki_page(file_name: str, section_target: str, new_content: str) -> str:
    """
    Modifies or appends content to a specific section within a standard wiki page.
    Creates the file or section dynamically if they do not exist.
    """
    file_name = file_name.strip(" '\"`‌")
    if not file_name.endswith('.md'):
        file_name += '.md'
        
    file_path = os.path.join(WIKI_DIR, file_name)
    new_content = new_content.strip()
    
    # Step 1: If the file doesn't exist at all, create it with a main title and the new section
    if not os.path.exists(file_path):
        formatted_header = section_target.strip()
        if not formatted_header.startswith('#'):
            formatted_header = f"## {formatted_header}"
            
        # Create a clean Page Title based on the filename (e.g., 'mec_taxe' -> 'Mec Taxe')
        page_title = file_name.replace('.md', '').replace('_', ' ').title()
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(f"# {page_title}\n\n")
            f.write(f"{formatted_header}\n{new_content}\n")
            
        return f"✅ Fișierul '{file_name}' nu exista. L-am creat automat cu titlul '{page_title}' și am adăugat secțiunea solicitată."

    # Step 2: Read existing content
    with open(file_path, 'r', encoding='utf-8') as f:
        full_text = f.read()
        
    # Prevent exact duplicate insertions to keep the AI from looping identical data
    if new_content in full_text:
        return f"ℹ️ Conținutul propus există deja în '{file_name}'. Nu a fost duplicat."
        
    with open(file_path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    target_clean = clean_header(section_target)
    section_found = False
    insert_index = len(lines)  # Default to appending at the end of the file
    
    # Step 3: Find the target section and determine where it ends
    for idx, line in enumerate(lines):
        if line.strip().startswith('#') and clean_header(line) == target_clean:
            section_found = True
            # Look ahead to find the start of the NEXT section
            for next_idx in range(idx + 1, len(lines)):
                if lines[next_idx].strip().startswith('#'):
                    insert_index = next_idx
                    break
            break

    # Step 4: Insert the content
    if section_found:
        # Insert right before the next section begins (or at the EOF)
        lines.insert(insert_index, f"\n{new_content}\n")
        with open(file_path, 'w', encoding='utf-8') as f:
            f.writelines(lines)
        return f"✅ Succes: Am adăugat informațiile la finalul secțiunii '{section_target}' din fișierul '{file_name}'."
    else:
        # If the section doesn't exist, append it at the bottom of the document
        formatted_header = section_target.strip()
        if not formatted_header.startswith('#'):
            formatted_header = f"## {formatted_header}"
            
        lines.append(f"\n{formatted_header}\n")
        lines.append(f"{new_content}\n")
        
        with open(file_path, 'w', encoding='utf-8') as f:
            f.writelines(lines)
        return f"✅ Succes: Secțiunea '{section_target}' nu exista, așa că am creat-o la finalul fișierului '{file_name}' și am inserat textul."

def list_pages() -> str:
    """
    Returns all wiki pages currently available.
    """

    if not os.path.exists(WIKI_DIR):
        return "Wiki-ul este gol."

    pages = sorted(
        f for f in os.listdir(WIKI_DIR)
        if f.endswith(".md")
    )

    if not pages:
        return "Wiki-ul este gol."

    return "\n".join(pages)

WIKI_LINK_PATTERN = re.compile(
    r"\[\[([^\]]+)\]\]"
)

def find_pages(query: str, max_results: int = 20) -> str:
    """
    Finds pages whose filenames contain the query.
    Useful before READ_PAGE.
    """

    query = query.lower().strip()

    if not query:
        return "❌ Query goală."

    if not os.path.exists(WIKI_DIR):
        return "Wiki-ul este gol."

    matches = []

    for page in os.listdir(WIKI_DIR):

        if not page.endswith(".md"):
            continue

        filename = page.lower()

        if query in filename:
            matches.append(page)

    matches = sorted(matches)

    if not matches:
        return f"ℹ️ Nu există pagini care conțin '{query}'."

    matches = matches[:max_results]

    return "\n".join(matches)

def search_links(file_name: str) -> str:
    """
    Returns all wiki-links found inside a page.
    """

    file_name = file_name.strip(" '\"`")

    if not file_name.endswith(".md"):
        file_name += ".md"

    path = os.path.join(
        WIKI_DIR,
        file_name
    )

    if not os.path.exists(path):
        return f"❌ Fișierul '{file_name}' nu există."

    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()

        links = sorted(
            set(
                WIKI_LINK_PATTERN.findall(content)
            )
        )

        if not links:
            return (
                f"ℹ️ Pagina '{file_name}' "
                f"nu conține wiki-links."
            )

        return "\n".join(links)

    except Exception as e:
        return (
            f"❌ Error reading '{file_name}': "
            f"{str(e)}"
        )
    

MAX_AGENT_STEPS = 30

TOOL_PATTERN = re.compile(
    r"<tool>\s*(.*?)\s*</tool>",
    re.DOTALL
)


def execute_tool(tool_text):

    try:

        lines = [
            x.strip()
            for x in tool_text.splitlines()
            if x.strip()
        ]

        tool_name = lines[0]

        if tool_name == "READ_PAGE":
            file_name = lines[1]
            return read_wiki_page(file_name)

        elif tool_name == "CREATE_PAGE":        

            file_name = lines[1]
            content = tool_text.split("---", 1)[1]
            target = os.path.join(
                WIKI_DIR,
                file_name
            )
            if os.path.exists(target):
                return (
                    f"❌ Pagina '{file_name}' există deja. "
                    f"Folosește UPDATE_PAGE."
                )
            with open(target, "w", encoding="utf-8") as f:
                f.write(content.strip())
            return f"✅ Created {file_name}"
        
        elif tool_name == "UPDATE_PAGE":

            file_name = lines[1]
            section_line = next(
                x for x in lines
                if x.startswith("SECTION:")
            )
            section = section_line.replace(
                "SECTION:",
                ""
            ).strip()
            content = tool_text.split("---", 1)[1]
            return patch_wiki_page(
                file_name,
                section,
                content
            )
        
        elif tool_name == "UPDATE_INDEX":
            section_line = next(
                x for x in lines
                if x.startswith("SECTION:")
            )
            section = section_line.replace(
                "SECTION:",
                ""
            ).strip()
            content = tool_text.split("---", 1)[1]
            return patch_index(
                section,
                content
            )
        elif tool_name == "LIST_PAGES":
            return list_pages()
        
        elif tool_name == "SEARCH_LINKS":
            file_name = lines[1]
            return search_links(file_name)
        
        elif tool_name == "FIND_PAGES":
            query = lines[1]
            return find_pages(query)
        
        return f"❌ Unknown tool: {tool_name}"
    
    except Exception as e:
        return f"❌ Tool error: {str(e)}"

